# Generated by Django 2.2.4 on 2019-08-21 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageupload', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadimage',
            name='description',
            field=models.CharField(default='Shopping Notes', max_length=50),
        ),
        migrations.AddField(
            model_name='uploadimage',
            name='header',
            field=models.CharField(default='Shopping Arg', max_length=50),
        ),
    ]
